### ISSUE TITLE
Items are lost when a player dies on negative Y level

### ISSUE THREAD

**Issue by Dimitar5555** [PneumonoIsNotAvailable/Gravestones#11]
When a player dies on negative Y level, no gravestone is generated and all items are lost. The log says that the items have been dropped on the floor but there is nothing. The first such case caused a server crash, subsequent tests on the same mod version (1.0.6), and on the latest mod version (1.0.8) didn't crash the server. Using Minecraft 1.21.

<details>
<summary>First case (caused server crash, mod version 1.0.6)</summary>

[19:00:56] [Server thread/INFO]: Rado332 was killed by Witch using magic
[19:00:56] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1025) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:299) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2338.method_10263()" because "pos" is null
	at net.pneumono.gravestones.gravestones.GravestonePosition.<init>(GravestonePosition.java:14) ~[gravestones-1.0.6.jar:?]
	at net.pneumono.gravestones.gravestones.GravestoneCreation.readAndWriteData(GravestoneCreation.java:229) ~[gravestones-1.0.6.jar:?]
	at net.pneumono.gravestones.gravestones.GravestoneCreation.handleGravestones(GravestoneCreation.java:119) ~[gravestones-1.0.6.jar:?]
	at net.minecraft.class_1657.handler$zmb000$gravestones$spawnGravestone(class_1657.java:4427) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_16078(class_1657.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_16080(class_1309.java:1437) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_6078(class_3222.java:725) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_5643(class_1309.java:1252) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_5643(class_1657.java:977) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_5643(class_3222.java:811) ~[server-intermediary.jar:?]
	at net.minecraft.class_8632.method_5564(class_8632.java:36) ~[server-intermediary.jar:?]
	at net.minecraft.class_1686.method_7498(class_1686.java:154) ~[server-intermediary.jar:?]
	at net.minecraft.class_1686.method_7488(class_1686.java:102) ~[server-intermediary.jar:?]
	at net.minecraft.class_1676.method_59860(class_1676.java:182) ~[server-intermediary.jar:?]
	at net.minecraft.class_1682.method_5773(class_1682.java:49) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_18762(class_3218.java:770) ~[server-intermediary.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:498) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_31420(class_3218.java:408) ~[server-intermediary.jar:?]
	at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:372) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021) ~[server-intermediary.jar:?]
	... 5 more
[19:00:56] [Server thread/ERROR]: This crash report has been saved to: /home/dimitar/Downloads/MC_SERVER_TEST/crash-reports/crash-2024-07-15_19.00.56-server.txt

</details>

<details>
<summary>Crash report</summary>

---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 2024-07-15 19:00:56
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2338.method_10263()" because "pos" is null
	at net.pneumono.gravestones.gravestones.GravestonePosition.<init>(GravestonePosition.java:14)
	at net.pneumono.gravestones.gravestones.GravestoneCreation.readAndWriteData(GravestoneCreation.java:229)
	at net.pneumono.gravestones.gravestones.GravestoneCreation.handleGravestones(GravestoneCreation.java:119)
	at net.minecraft.class_1657.handler$zmb000$gravestones$spawnGravestone(class_1657.java:4427)
	at net.minecraft.class_1657.method_16078(class_1657.java)
	at net.minecraft.class_1309.method_16080(class_1309.java:1437)
	at net.minecraft.class_3222.method_6078(class_3222.java:725)
	at net.minecraft.class_1309.method_5643(class_1309.java:1252)
	at net.minecraft.class_1657.method_5643(class_1657.java:977)
	at net.minecraft.class_3222.method_5643(class_3222.java:811)
	at net.minecraft.class_8632.method_5564(class_8632.java:36)
	at net.minecraft.class_1686.method_7498(class_1686.java:154)
	at net.minecraft.class_1686.method_7488(class_1686.java:102)
	at net.minecraft.class_1676.method_59860(class_1676.java:182)
	at net.minecraft.class_1682.method_5773(class_1682.java:49)
	at net.minecraft.class_3218.method_18762(class_3218.java:770)
	at net.minecraft.class_1937.method_18472(class_1937.java:498)
	at net.minecraft.class_3218.method_31420(class_3218.java:408)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:372)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
	at net.minecraft.class_3176.method_3813(class_3176.java:299)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.pneumono.gravestones.gravestones.GravestonePosition.<init>(GravestonePosition.java:14)
	at net.pneumono.gravestones.gravestones.GravestoneCreation.readAndWriteData(GravestoneCreation.java:229)
	at net.pneumono.gravestones.gravestones.GravestoneCreation.handleGravestones(GravestoneCreation.java:119)
	at net.minecraft.class_1657.handler$zmb000$gravestones$spawnGravestone(class_1657.java:4427)
	at net.minecraft.class_1657.method_16078(class_1657.java)
	at net.minecraft.class_1309.method_16080(class_1309.java:1437)
	at net.minecraft.class_3222.method_6078(class_3222.java:725)
	at net.minecraft.class_1309.method_5643(class_1309.java:1252)
	at net.minecraft.class_1657.method_5643(class_1657.java:977)
	at net.minecraft.class_3222.method_5643(class_3222.java:811)
	at net.minecraft.class_8632.method_5564(class_8632.java:36)
	at net.minecraft.class_1686.method_7498(class_1686.java:154)
	at net.minecraft.class_1686.method_7488(class_1686.java:102)
	at net.minecraft.class_1676.method_59860(class_1676.java:182)
	at net.minecraft.class_1682.method_5773(class_1682.java:49)
	at net.minecraft.class_3218.method_18762(class_3218.java:770)
	at net.minecraft.class_1937.method_18472(class_1937.java:498)
	at net.minecraft.class_3218.method_31420(class_3218.java:408)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)

-- Entity being ticked --
Details:
	Entity Type: minecraft:potion (net.minecraft.class_1686)
	Entity ID: 70785
	Entity Name: Potion
	Entity's Exact location: -2787.10, -51.99, 1843.99
	Entity's Block location: World: (-2788,-52,1843), Section: (at 12,12,3 in -175,-4,115; chunk contains blocks -2800,-64,1840 to -2785,319,1855), Region: (-6,3; contains chunks -192,96 to -161,127, blocks -3072,-64,1536 to -2561,319,2047)
	Entity's Momentum: 0.63, 0.17, -0.36
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:498)
	at net.minecraft.class_3218.method_31420(class_3218.java:408)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:372)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
	at net.minecraft.class_3176.method_3813(class_3176.java:299)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Rado332'/46148, l='ServerLevel[MC server 1.21 2024-07]', x=-2786.26, y=-53.97, z=1843.70]]
	Chunk stats: 3050
	Level dimension: minecraft:overworld
	Level spawn location: World: (-48,7,-112), Section: (at 0,7,0 in -3,0,-7; chunk contains blocks -48,-64,-112 to -33,319,-97), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 1697972 game time, 2508930 day time
	Level name: MC server 1.21 2024-07
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Commands: false
	Level weather: Rain time: 24859 (now: false), thunder time: 31501 (now: false)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Loaded entity count: 366
Stacktrace:
	at net.minecraft.class_3218.method_8538(class_3218.java:1693)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1024)
	at net.minecraft.class_3176.method_3813(class_3176.java:299)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Linux (amd64) version 5.15.0-113-generic
	Java Version: 21.0.3, Ubuntu
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Ubuntu
	Memory: 832681176 bytes (794 MiB) / 1436549120 bytes (1370 MiB) up to 3101687808 bytes (2958 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 1.60
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: UHD Graphics 620
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MiB): 256.00
	Graphics card #0 deviceId: 0x5917
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MiB): 7963.66
	Virtual memory used (MiB): 6062.57
	Swap memory total (MiB): 2048.00
	Swap memory used (MiB): 260.55
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 46643.04, total: 111598.16
	Space in storage for workdir (MiB): available: 46643.04, total: 111598.16
	JVM Flags: 0 total; 
	Fabric Mods: 
		balm-fabric: Balm 21.0.14
			kuma_api: KumaAPI 21.0.4
		bundle_recipe: Bundle Recipe v1.0.3
		collective: Collective 7.70
		constructionwand: Construction Wand (Fabric) 1.0.1
			forgeconfigapiport: Forge Config API Port 21.0.0
				com_electronwill_night-config_core: core 3.6.7
				com_electronwill_night-config_toml: toml 3.6.7
		doubledoors: Double Doors 5.8
		fabric-api: Fabric API 0.100.3+1.21
			fabric-api-base: Fabric API Base 0.4.42+6573ed8cd1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.67+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.28+6fc22b99d1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.48+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.27+6a6dfa19d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.65+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.13+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.14+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.3.1+8a3b5617d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.23+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.8+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10+e633f883d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.52+6573ed8cd1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.1+cb5ced13d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.11+8f3583aed1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.10+6573ed8cd1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.0+ab7edbacd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.11+d1321076d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.9+6573ed8cd1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.22+ab7edbacd1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1+d153f344d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.1.4+cb5ced13d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.79+b5597344d1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.14+b5597344d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12+6573ed8cd1
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		gravestones: Gravestones 1.0.6
		java: OpenJDK 64-Bit Server VM 21
		jei: Just Enough Items 19.5.0.31
		journeymap: Journeymap 1.21-6.0.0-beta.8
			ar_com_hjg_pngj: pngj 2.1.0
			commonnetworking: Common Network 1.0.11-1.21
			journeymap-api-fabric: JourneyMap API 2.0.0-1.21-SNAPSHOT
		leaves_us_in_peace: Leaves Us In Peace 1.1.0
		minecraft: Minecraft 1.21
		owo: oωo 0.12.10+1.21
			blue_endless_jankson: jankson 1.2.2
			io_wispforest_endec: endec 0.1.0
			io_wispforest_endec_gson: gson 0.1.0
			io_wispforest_endec_jankson: jankson 0.1.0
			io_wispforest_endec_netty: netty 0.1.0
		pneumonocore: PneumonoCore 1.1.6
	Server Running: true
	Player Count: 1 / 20; [class_3222['Rado332'/46148, l='ServerLevel[MC server 1.21 2024-07]', x=-2786.26, y=-53.97, z=1843.70]]
	Active Data Packs: vanilla, fabric, balm-fabric (incompatible), bundle_recipe, collective, constructionwand (incompatible), fabric-convention-tags-v2, gravestones, leaves_us_in_peace, leaves_us_in_peace:oak_leaves_recognize_jungle_logs
	Available Data Packs: balm-fabric (incompatible), bundle, bundle_recipe, collective, constructionwand (incompatible), fabric, fabric-convention-tags-v2, gravestones, leaves_us_in_peace, leaves_us_in_peace:oak_leaves_recognize_jungle_logs, leaves_us_in_peace:wood_prevents_decay, trade_rebalance, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: 7445395903252703439
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

</details>

<details>
<summary>Manual test (didn't cause crash, mod version 1.0.8)</summary>

20:13:41] [Server thread/INFO]: Luna16 was slain by kris
[20:13:41] [Server thread/INFO]: ----- ----- Beginning Gravestone Work ----- -----
[20:13:41] [Server thread/INFO]: This mostly exists for debugging purposes, but might be useful for server owners. If you don't want to see all this every time someone dies, disable 'console_info' in the config!
[20:13:41] [Server thread/ERROR]: Gravestone was not placed successfully! The items have been dropped on the floor
[20:13:41] [Server thread/INFO]: Reading gravestone data file
[20:13:41] [Server thread/INFO]: Updating data/creating new data
[20:13:41] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2824@29e2ff3f, suppressing error
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2338.method_10263()" because "pos" is null
	at net.pneumono.gravestones.gravestones.GravestonePosition.<init>(GravestonePosition.java:14) ~[gravestones-1.0.6.jar:?]
	at net.pneumono.gravestones.gravestones.GravestoneCreation.readAndWriteData(GravestoneCreation.java:227) ~[gravestones-1.0.6.jar:?]
	at net.pneumono.gravestones.gravestones.GravestoneCreation.handleGravestones(GravestoneCreation.java:119) ~[gravestones-1.0.6.jar:?]
	at net.minecraft.class_1657.handler$zmb000$gravestones$spawnGravestone(class_1657.java:4427) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_16078(class_1657.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_16080(class_1309.java:1437) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_6078(class_3222.java:725) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_5643(class_1309.java:1252) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_5643(class_1657.java:977) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_5643(class_3222.java:811) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_7324(class_1657.java:1303) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_7324(class_3222.java:1743) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244$1.method_34218(class_3244.java:1650) ~[server-intermediary.jar:?]
	at net.minecraft.class_2824$1.method_34213(class_2824.java:174) ~[server-intermediary.jar:?]
	at net.minecraft.class_2824.method_34209(class_2824.java:74) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_12062(class_3244.java:1610) ~[server-intermediary.jar:?]
	at net.minecraft.class_2824.method_12251(class_2824.java:61) ~[server-intermediary.jar:?]
	at net.minecraft.class_2824.method_11054(class_2824.java:15) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:27) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:162) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:136) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:145) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18857(MinecraftServer.java:810) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:815) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

</details>

**Comment by PneumonoIsNotAvailable** [comment]
I can recreate this on 1.0.6, but it seems fixed on 1.0.8. Looking at the 1.0.8 crashlog you sent, it mentions "gravestones-1.0.6.jar", so most likely there was just a mistake with updating. If the problem persists, reply and we can reopen the issue!

**Comment by Dimitar5555** [comment]
Indeed, my bad. I haven't updated the server's mod file properly. It works as expected now.
